### ISSUE TITLE
Quick test

### ISSUE THREAD

**Issue by lionfish0** [lionfish0/daskec2lite#2]
from jpoullet2000 (copied from [here](https://github.com/dask/dask-ec2/issues/98#issuecomment-387774538))
After a quick test here is the error I get (dasklite)

`jbp@jbp-XPS-L521X:~$ daskec2lite --pathtokeyfile ~/.ssh/datascience.pem --keyname datascience --username ubuntu --numinstances 2 --instancetype c4.2xlarge --region eu-west-1 --imageid ami-c8b51fb1 --wpi 2 --sgid sg-c18336bc --spotprice 3 

Traceback (most recent call last):   
File "/home/jbp/miniconda3/envs/dasklite/bin/daskec2lite", line 11, in <module>     sys.exit(main())  
 File "/home/jbp/miniconda3/envs/dasklite/lib/python3.6/site-packages/daskec2lite/daskec2lite.py", line 180, in main imageid=args.imageid,keyname=args.keyname,spotprice=args.spotprice,region_name=args.region_name)    
File "/home/jbp/miniconda3/envs/dasklite/lib/python3.6/site-packages/daskec2lite/daskec2lite.py", line 28, in start_cluster     'SecurityGroupIds': [ sgid ]   
File "/home/jbp/miniconda3/envs/dasklite/lib/python3.6/site-packages/botocore/client.py", line 314, in _api_call     return self._make_api_call(operation_name, kwargs)  
 File "/home/jbp/miniconda3/envs/dasklite/lib/python3.6/site-packages/botocore/client.py", line 612, in _make_api_call     raise error_class(parsed_response, operation_name) 

botocore.exceptions.ClientError: An error occurred (InvalidGroup.NotFound) when calling the RequestSpotInstances operation: The security group 'sg-9146afe9' does not exist in VPC 'vpc-a72c1ec0'`

**Comment by lionfish0** [comment]
Hi,
There'll be a lot of bugs like this at the moment - I just made this for myself for my current project - will hopefully get to tidy it up soon.

Bug is due to line 179 where I'm not passing the sgid to the start_cluster method. I also have some unnecessarily defaulted parameters in the method.

https://github.com/lionfish0/daskec2lite/blob/914c3f00836d06907a623e745e303b985a938a6c/daskec2lite/daskec2lite.py#L179

**Comment by lionfish0** [comment]
Fixed in commit: https://github.com/lionfish0/daskec2lite/commit/3336e807457511996801f7df65f5030c186ea3e4
